DROP TABLE IF EXISTS BLEAT_USERS CASCADE;
DROP TABLE IF EXISTS BLEATS;
-- Table: USERS
CREATE TABLE BLEAT_USERS (
    ID SERIAL PRIMARY KEY NOT NULL, 
    USER_NAME TEXT NOT NULL, 
    EMAIL TEXT NOT NULL,
    FAVORITE_THING TEXT NOT NULL);
INSERT INTO BLEAT_USERS (ID, USER_NAME, EMAIL, FAVORITE_THING) VALUES (1, 'SarahZ', 'sarah@email.com', 'Vegetables');
INSERT INTO BLEAT_USERS (ID, USER_NAME, EMAIL, FAVORITE_THING) VALUES (2, 'SansUndertale', 'humerus@email.com', 'A good time');
INSERT INTO BLEAT_USERS (ID, USER_NAME, EMAIL, FAVORITE_THING) VALUES (3, 'Boba', 'boba@email.com', 'disintegration');
INSERT INTO BLEAT_USERS (ID, USER_NAME, EMAIL, FAVORITE_THING) VALUES (4, 'Jeffie', 'jeffa@email.com', 'Teppen');
INSERT INTO BLEAT_USERS (ID, USER_NAME, EMAIL, FAVORITE_THING) VALUES (5, 'Jegbert', 'jegbert@sburb.com', 'Nicholas Cage');

ALTER SEQUENCE bleat_users_id_seq RESTART WITH 6;
-- Table: BLEATS
CREATE TABLE BLEATS (
    ID SERIAL PRIMARY KEY NOT NULL, 
    USER_ID INTEGER NOT NULL REFERENCES BLEAT_USERS (ID), 
    BLEAT_CONTENT TEXT NOT NULL
    );
INSERT INTO BLEATS ( USER_ID, BLEAT_CONTENT) VALUES ( 2, 'want some fried snow?');
INSERT INTO BLEATS ( USER_ID, BLEAT_CONTENT) VALUES ( 2, 'i just baked 1000000 pies. do you want any?');
INSERT INTO BLEATS ( USER_ID, BLEAT_CONTENT) VALUES ( 2, 'is your refrigerator running?');
INSERT INTO BLEATS ( USER_ID, BLEAT_CONTENT) VALUES ( 1, 'sometimes weirdos put whoopee cushions on the seats.');
INSERT INTO BLEATS ( USER_ID, BLEAT_CONTENT) VALUES ( 1, 'grillby, we''ll have a double order of burg.');
INSERT INTO BLEATS ( USER_ID, BLEAT_CONTENT) VALUES ( 3, 'I''M HONORED TO BE IN THE PRESENCE OF SUCH A HUGE LUKEWARM WATER FAN, FOLKS!');
INSERT INTO BLEATS ( USER_ID, BLEAT_CONTENT) VALUES ( 3, 'I''VE HEARD THAT LIKE THE OTHER FILMS...IT CONSISTS MOSTLY OF A SINGLE FOUR-HOUR SHOT OF ROSE PETALS SHOWERING ON MY RECLINING BODY.');
INSERT INTO BLEATS ( USER_ID, BLEAT_CONTENT) VALUES ( 3, 'YOU WOULDN''T (COUGH) SPOIL MY MOVIE FOR EVERYONE WITH A PROMOTIONAL STORY, WOULD YOU?');
INSERT INTO BLEATS ( USER_ID, BLEAT_CONTENT) VALUES ( 4, 'Up until now, I''ve only been using a fraction of my REAL power!');
INSERT INTO BLEATS ( USER_ID, BLEAT_CONTENT) VALUES ( 4, 'DID YOU FORGET WHAT THE GREEN TILES DO?');
INSERT INTO BLEATS ( USER_ID, BLEAT_CONTENT) VALUES ( 5, 'WELL, WELL, WELL.');
INSERT INTO BLEATS ( USER_ID, BLEAT_CONTENT) VALUES ( 5, 'WELLY WELL WELL.');
INSERT INTO BLEATS ( USER_ID, BLEAT_CONTENT) VALUES ( 5, 'WELL WELLY WELL WELL, WELL WELL WELLY.');
INSERT INTO BLEATS ( USER_ID, BLEAT_CONTENT) VALUES ( 4, 'YOU NEVER STEPPED ON A GREEN TILE.');
INSERT INTO BLEATS ( USER_ID, BLEAT_CONTENT) VALUES ( 1, 'CONGRATULATIONS!');